### ISSUE TITLE
你好问下 我想自定义时间 我的时间是30秒一次 这个可以实现吗

### ISSUE THREAD

**Issue by by05021** [thelostword/timeline#1]
你好问下 我想自定义时间 我的时间是30秒一次 这个可以实现吗

**Comment by thelostword** [comment]
> 你好问下 我想自定义时间 我的时间是30秒一次 这个可以实现吗

没太明白你说的 `30秒一次` 是什么意思。
如果需要时间刻度间隔固定 `30s` 的话可以设置 `zoom/maxZoom/minZoom` 固定为 `3`

**Comment by dez0514** [comment]
你好  zoom/maxZoom/minZoom 相等时，比如都为3，初始化整个都没内容，要滚轮滚一下之后内容出来。。

**Comment by thelostword** [comment]
> 你好 zoom/maxZoom/minZoom 相等时，比如都为3，初始化整个都没内容，要滚轮滚一下之后内容出来。。

这个问题已经修复，感谢提出。
