### ISSUE TITLE
如何通过外部传入一个时间戳，重新绘制

### ISSUE THREAD

**Issue by lydat** [thelostword/timeline#3]
比如这个场景用于视频播放，视频会传入要给时间戳，实时绘制

**Comment by thelostword** [comment]
![image](https://user-images.githubusercontent.com/41263837/208369110-5d56edb6-bad8-4ebb-b970-a266d233717f.png)
调用这个方法
timeline.draw({
  currentTime: 1651829532,
});

**Comment by lydat** [comment]
> ![image](https://user-images.githubusercontent.com/41263837/208369110-5d56edb6-bad8-4ebb-b970-a266d233717f.png) 调用这个方法 timeline.draw({ currentTime: 1651829532, });

应该单独抽离出个方法，不然areas这样好像会变成空

**Comment by ljzorz** [comment]
是啊，没有抽离出来每次都要绘制areas
