### ISSUE TITLE
当第二次鼠标拖动的时候，有可能被识别成拖拽事件，不会触发document.onmouseup

### ISSUE THREAD

**Issue by lydat** [thelostword/timeline#4]
长按鼠标向上拖拽的时候，会触发H5原生的拖拽事件。并且不会监听到document.onmouseup。这样会造成一个当松开鼠标的时候会造成时间轴跟着鼠标的运动轨迹去横向移动。

**Comment by thelostword** [comment]
有复现地址吗，以及环境。我这边测试未发现问题

**Comment by lydat** [comment]
没弄了，当时我直接把拖拽事件设为空了
