### ISSUE TITLE
无法使用,vue3引入报错了

### ISSUE THREAD

**Issue by LECYWZA** [thelostword/timeline#8]
@losting_timeline.js?v=10430adf:526 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getContext')
![image](https://github.com/user-attachments/assets/7432933a-3eb7-4fd1-baa0-f71a8895997c)

这句报错了
![image](https://github.com/user-attachments/assets/b1437467-6417-4d27-93bc-95cb84b196de)

**Comment by thelostword** [comment]
能否提供下完整代码，以及使用的版本？

**Comment by thelostword** [comment]
看代码是在Vue中使用，`new Timeline()` 要在mounted后使用，否则会找不到DOM。 `document.querySelector('#Timeline')` 会返回 `null`

**Comment by yuzhouzhijia520** [comment]
vue中直接设置id，用‘#id’就好了
